// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechAptV1.Client.Data;

#nullable disable

namespace TechAptV1.Client.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250211184337_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("TechAptV1.Client.Models.Number", b =>
                {
                    b.Property<int>("IsPrime")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.ToTable("Numbers");
                });
#pragma warning restore 612, 618
        }
    }
}
